name = "NetworkX"
uuid = "e7c81c0a-5e4f-4e76-9e2a-8c3f7a1b2d3e"
version = "0.1.0"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
CondaPkg = "0.2"
Graphs = "1.12"
PythonCall = "0.9"
julia = "1.10"
